# Generated by Django 4.1.7 on 2023-03-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
    ]
