# Generated by Django 4.1.7 on 2023-03-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_contect_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_name',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
